#!/bin/sh

LAUNCHER_DIR="";
for base in /usr /usr/local /usr/pkg /opt /app; do
    for sub in "share/suika3/launcher" \
               "share/doc/suika3/launcher" \
               "share/docs/suika3/launcher"; do
        target="$base/$sub";
        if [ -d "$target" ]; then
            LAUNCHER_DIR="$target";
            break 2;
        fi
    done
done

if [ -z "$LAUNCHER_DIR" ]; then
    echo "No launcher directory found.";
    exit 1;
fi

cd "$LAUNCHER_DIR" && suika3
