.\" suika3.1.mdoc - Suika3 manpage
.Dd January 2026
.Dt SUIKA3 1
.Os Suika3 1.0
.Sh NAME
.Nm suika3
.Nd Cross-platform scripting VM for visual novels
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
is a cross-platform scripting VM for visual novels.
.Pp
When invoked,
.Nm
automatically executes the script
.Pa main.pf
from the current working directory.
No other script files can be specified on the command line.
.Sh EXAMPLES
Run the engine in a project directory containing
.Pa main.pf :
.Bd -literal -offset indent
cd mygame/
suika3
.Ed
.Sh SEE ALSO
.Xr suika3-compiler 1 ,
.Xr suika3-pack 1
.Sh AUTHORS
.An Awe Morris Aq Mt awe@noctvm.io
and contributors.
Project homepage:
.Lk https://github.com/suika3-community/suika3
