.\" suika3.1.mdoc - Suika3 manpage
.Dd January 2026
.Dt SUIKA3 1
.Os Suika3 1.0
.Sh NAME
.Nm suika3-launcher
.Nd Cross-platform scripting VM for visual novels
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
is a cross-platform scripting VM for visual novels.
.Pp
When invoked,
.Nm
starts the Suika3 launcer.
.Pp
If a file or a directory is specified as a command line argument,
it starts the game in the specified place.
.Sh SEE ALSO
.Xr suika3 (1),
.Xr suika3-bcc (1),
.Xr suika3-aotc (1),
.Xr suika3-pack (1)
.Sh AUTHORS
.An Awe Morris Aq Mt awe@noctvm.io
and contributors.
Project homepage:
.Lk https://github.com/awemorris/suika3
