.\" suika3-bcc.1 - Suika3 bytecode compiler manpage
.TH SUIKA3-BCC 1 "April 2026" "Suika3 26.07" "User Commands"
.SH NAME
suika3-bcc \- compile Ray scripts into bytecode files
.SH SYNOPSIS
.B suika3-bcc
[\fIsourcefiles...\fR]

.SH DESCRIPTION
The
.B suika3-bcc
translates Ray scripts (\fB.ray\fR) into bytecode files
with the extension \fB.pfc\fR.

Each input file is compiled independently. The output file has the same
basename as the input, with its extension replaced by \fB.pfc\fR.
For example, compiling
.I main.ray
produces
.I main.pfc
in the same directory.

.SH EXAMPLES
Compile a single script:
.EX
suika3-bcc main.ray
.EE

Compile multiple scripts:
.EX
suika3-bcc main.ray enemy.ray level.ray
.EE

The above command produces:
.EX
main.pfc enemy.pfc level.pfc
.EE

.SH SEE ALSO
.BR suika3 (1),
.BR suika3-aotc (1),
.BR suika3-pack (1)

.SH AUTHORS
Awe Morris <awe@noctvm.io> and contributors.
Project homepage: <https://github.com/awemorris/suika3>
