.\" suika3-aotc.1.mdoc - Suika3 AOT compiler manpage
.Dd January 2026
.Dt SUIKA3-COMPILER 1
.Os Suika3 1.0
.Sh NAME
.Nm suika3-aotc
.Nd compile Ray scripts into a C source file
.Sh SYNOPSIS
.Nm
.Op Ar sourcefiles ...
.Sh DESCRIPTION
The
.Nm
translates Ray script files
.Pa .ray
into a C source file named
.Pa library.c
.Pp
.Sh EXAMPLES
Compile a single script:
.Bd -literal -offset indent
suika3-aotc main.ray
.Ed
.Pp
Compile multiple scripts:
.Bd -literal -offset indent
suika3-aotc main.ray enemy.ray level.ray
.Ed
.Sh SEE ALSO
.Xr suika3 1 ,
.Xr suika3-bcc 1
.Xr suika3-pack 1
.Sh AUTHORS
.An Awe Morris Aq Mt awe@noctvm.io
and contributors.
Project homepage:
.Lk https://github.com/awemorris/suika3
