set(CMAKE_SYSTEM_NAME DOS)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_COMPILER wcl386)
set(CMAKE_CXX_COMPILER wcl386)

set(CMAKE_C_COMPILER_TARGET dos)
set(CMAKE_CXX_COMPILER_TARGET dos)

set(CMAKE_C_FLAGS_INIT "-bt=dos -ox -oe=200 -zp4 -fpi87")
set(CMAKE_CXX_FLAGS_INIT "-bt=dos")

set(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_C_COMPILER> <FLAGS> -bt=dos -l=dos4g -k32768 -fe=<TARGET> <OBJECTS> <LINK_LIBRARIES>"
    CACHE STRING "C link command" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_USER_MAKE_RULES_OVERRIDE
    "${CMAKE_CURRENT_LIST_DIR}/openwatcom-dos4gw-override.cmake")
