name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-vs2022:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          cmake --preset windows-vs2022-x86
          cmake --build --preset windows-vs2022-x86 --config Release
          cp out/build/windows-vs2022-x86/Release/suika3.exe suika3-win32.exe

          cmake --preset windows-vs2022-x64
          cmake --build --preset windows-vs2022-x64 --config Release
          cp out/build/windows-vs2022-x64/Release/suika3.exe suika3-win64.exe
          cp out/build/windows-vs2022-x64/Release/suika3-aotc.exe suika3-aotc.exe
          cp out/build/windows-vs2022-x64/Release/suika3-bcc.exe suika3-bcc.exe
          cp out/build/windows-vs2022-x64/Release/suika3-pack.exe suika3-pack.exe
          cp out/build/windows-vs2022-x64/Release/suika3-web.exe suika3-web.exe

          cmake --preset windows-vs2022-x64-console
          cmake --build --preset windows-vs2022-x64-console --config Release
          cp out/build/windows-vs2022-x64-console/Release/suika3.exe suika3-debug.exe

          cmake --preset windows-vs2022-arm64
          cmake --build --preset windows-vs2022-arm64 --config Release
          cp out/build/windows-vs2022-arm64/Release/suika3.exe suika3-arm64.exe

      - name: Upload Windows EXEs
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: |
            suika3-win32.exe
            suika3-win64.exe
            suika3-arm64.exe
            suika3-aotc.exe
            suika3-bcc.exe
            suika3-pack.exe
            suika3-web.exe
          if-no-files-found: error
          retention-days: 7

  build-windows-mingw-w64:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Download mingw-w64-11.0
        run: |
          echo "Downloading mingw-w64-11.0 with a MSVCRT/XP configuration."
          wget https://noctvm.io/ci/mingw-w64-11.0.tar.bz2
          tar xJf mingw-w64-11.0.tar.bz2
          echo "$PWD/mingw-w64-11.0/bin" >> $GITHUB_PATH

      - name: Build for mingw-w64 i686
        run: |
          cmake --preset windows-mingw-x86
          cmake --build --preset windows-mingw-x86
          i686-w64-mingw32-strip build-mingw-x86/suika3.exe
          cp build-mingw-x86/suika3.exe suika3-win32.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mingw
          path: |
            suika3-win32.exe
          if-no-files-found: error
          retention-days: 7

  build-macos:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup for macOS
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATE_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Build for macOS
        run: |
          cmake --preset macos
          cmake --build --preset macos

          cmake --preset macos-lib
          cmake --build --preset macos-lib

          cmake --preset macos-cli
          cmake --build --preset macos-cli

      - name: Build for iOS
        run: |
          cmake --preset ios-device
          cmake --build --preset ios-device

          cmake --preset ios-simulator
          cmake --build --preset ios-simulator

      - name: Build macOS dmg
        shell: bash
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_SECRET: ${{ secrets.APP_PASSWORD }}
        run: |
          cd build-macos
          codesign --timestamp --options runtime --entitlements ../resources/macos/macos.entitlements --deep --force --sign "Developer ID Application" Suika3.app
          ditto -c -k --sequesterRsrc --keepParent Suika3.app Suika3.zip
          xcrun notarytool submit Suika3.zip --apple-id "$APPLE_ID" --team-id "$TEAM_ID" --password "$APP_SECRET" --wait
          xcrun stapler staple Suika3.app
          mkdir tmp
          cp -Rv Suika3.app tmp/Suika3.app
          hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname Suika3 Suika3.dmg
          codesign --sign "Developer ID Application" Suika3.dmg
          cd ..
          mv build-macos/Suika3.dmg .

      - name: Build macOS/iOS XCFramework
        run: |
          xcodebuild \
            -create-xcframework \
            -library build-macos-lib/libsuika3.a -headers include \
            -library build-ios-device/libsuika3.a -headers include \
            -library build-ios-simulator/libsuika3.a -headers include \
            -output Suika3.xcframework
          zip -r Suika3.xcframework.zip Suika3.xcframework

      - name: Build macOS project
        run: |
          mkdir macos
          mkdir macos/project
          mkdir macos/project/Resources
          mkdir macos/project/Resources/video
          cp resources/assets.arc macos/project/Resources/

          mkdir macos/project/Game.xcodeproj
          cp resources/projects/macos/Game.xcodeproj/project.pbxproj macos/project/Game.xcodeproj/

          mkdir macos/project/Game
          cp -R Suika3.xcframework macos/project/Game/
          cp -R resources/projects/macos/Game/Assets.xcassets macos/project/Game/
          cp resources/projects/macos/Game/main.m macos/project/Game/
          cp resources/macos/macos.entitlements macos/project/Game/Game.entitlements

          zip -r Suika3-macOS-Xcode.zip -r macos

      - name: Build iOS project
        run: |
          mkdir ios/Resources
          mkdir ios/Resources/video
          cp resources/assets.arc ios/Resources/

          mkdir ios/ios.xcodeproj
          cp resources/projects/ios/ios.xcodeproj/project.pbxproj ios/ios.xcodeproj/

          mkdir ios/ios
          cp -R Suika3.xcframework ios/ios/
          cp -R resources/projects/ios/ios/Assets.xcassets ios/ios/

          cp resources/projects/ios/ios/entry.c ios/ios/
          cp resources/projects/ios/ios/Info.plist ios/ios/
          cp resources/projects/ios/ios/ios.entitlements ios/ios/
          cp resources/projects/ios/ios/LaunchScreen.storyboard ios/ios/
          cp resources/ios/ExportOptions.plist ios/
          cp resources/ios/build.sh ios/

          zip -r Suika3-iOS-Xcode.zip -r ios

      - name: Build macOS tar.gz
        run: |
          mkdir -p out
          mkdir -p out/bin
          mkdir -p out/share/man/man1
          cp build-macos-cli/playfield out/bin/
          cp build-macos-cli/playfield-pack out/bin/
          cp build-macos-cli/playfield-aotc out/bin/
          cp build-macos-cli/playfield-bcc out/bin/
          cp resources/manpage/suika3.1
          cd out
          tar czf ../suika3-macos-universal.tar.gz *
          cd ..

      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: |
            Suika3.dmg
            Suika3-macOS-Xcode.zip
            Suika3-iOS-Xcode.zip
            suika3-macos-universal.tar.gz
          if-no-files-found: error
          retention-days: 7

  build-flatpak-x86_64:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder

      - name: Build flatpak
        run: |
          yes | flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.freedesktop.Sdk//25.08
          flatpak install --user -y flathub org.freedesktop.Platform//25.08
          flatpak install --user -y flathub org.freedesktop.Platform.GStreamer.openmpt//25.08
          flatpak-builder --user -y --repo=myrepo --force-clean build-dir-x86_64 ./resources/flatpak/vn.suika3.engine.yml
          flatpak build-bundle myrepo Suika3-x86_64.flatpak vn.suika3.engine --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-x86_64
          path: |
            Suika3-x86_64.flatpak
          if-no-files-found: error
          retention-days: 7

  build-flatpak-aarch64:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-24.04-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder

      - name: Build flatpak
        run: |
          yes | flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.freedesktop.Sdk//25.08
          flatpak install --user -y flathub org.freedesktop.Platform//25.08
          flatpak install --user -y flathub org.freedesktop.Platform.GStreamer.openmpt//25.08
          flatpak-builder --user -y --repo=myrepo --force-clean build-dir-aarch64 ./resources/flatpak/vn.suika3.engine.yml
          flatpak build-bundle myrepo Suika3-aarch64.flatpak vn.suika3.engine --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-aarch64
          path: |
            Suika3-aarch64.flatpak
          if-no-files-found: error
          retention-days: 7

  build-wasm:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup for Wasm
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build for Wasm
        run: |
          cmake --preset wasm
          cmake --build --preset wasm
          cp build-wasm/index.html ./  

      - name: Upload Wasm
        uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: |
            index.html
          if-no-files-found: error
          retention-days: 7

  build-android:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build openjdk-17-jdk gradle

      - name: Setup for Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build shared libraries
        run: |
          cmake --preset android-arm64
          cmake --build --preset android-arm64
          cmake --preset android-armv7
          cmake --build --preset android-armv7
          cmake --preset android-x86_64
          cmake --build --preset android-x86_64
          cmake --preset android-x86
          cmake --build --preset android-x86
          cmake --preset android-riscv64
          cmake --build --preset android-riscv64

      - name: Build project
        run: |
          mkdir android
          cp -R resources/projects/android/app                 android/
          cp -R resources/projects/android/gradle.properties   android/
          cp -R resources/projects/android/build.gradle        android/
          cp -R resources/projects/android/gradlew             android/
          cp -R resources/projects/android/settings.gradle     android/
          cp -R resources/projects/android/gradlew.bat         android/
          cp -R resources/projects/android/gradle              android/
          cp -R resources/projects/android/build.bat           android/
          cp -R resources/projects/android/build.sh            android/

          mkdir -p android/app/src/main/assets
          cp -R game/* android/app/src/main/assets/
          cp resources/launcher/system/font/NotoSans-Medium.ttf android/app/src/main/assets/system/font/NotoSansCJK-Medium.ttc

          mkdir -p android/app/src/main/java/io/noctvm/strato
          cp external/PlayfieldEngine/external/StratoHAL/src/MainActivity.java android/app/src/main/java/io/noctvm/strato/

          mkdir -p android/app/src/main/jniLibs/arm64-v8a
          cp build-android-arm64/libsuika3.so android/app/src/main/jniLibs/arm64-v8a/libstrato.so

          mkdir -p android/app/src/main/jniLibs/armeabi-v7a
          cp build-android-armv7/libsuika3.so android/app/src/main/jniLibs/armeabi-v7a/libstrato.so

          mkdir -p android/app/src/main/jniLibs/x86_64
          cp build-android-x86_64/libsuika3.so android/app/src/main/jniLibs/x86_64/libstrato.so

          mkdir -p /android/app/src/main/jniLibs/x86
          cp build-android-x86/libsuika3.so android/app/src/main/jniLibs/x86/libstrato.so

          mkdir -p /android/app/src/main/jniLibs/riscv64
          cp build-android-riscv64/libsuika3.so android/app/src/main/jniLibs/riscv64/libstrato.so

          zip -r Suika3-Android-Studio.zip android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64
          path: |
            Suika3-Android-Studio.zip
          if-no-files-found: error
          retention-days: 7

  build-openharmony:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: git submodule update --init

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build flex bison

      - name: Download OpenHarmony SDK
        run: |
          echo "Downloading openharmony-native.tar.gz"
          wget -q https://noctvm.io/ci/openharmony-native.tar.gz
          tar xzf openharmony-native.tar.gz

      - name: Build for OpenHarmony
        run: |
          OH_NATIVE_SDK_ROOT="$PWD/openharmony-sdk-native" cmake --preset openharmony-arm64
          OH_NATIVE_SDK_ROOT="$PWD/openharmony-sdk-native" cmake --build --preset openharmony-arm64
          OH_NATIVE_SDK_ROOT="$PWD/openharmony-sdk-native" cmake --preset openharmony-x86_64
          OH_NATIVE_SDK_ROOT="$PWD/openharmony-sdk-native" cmake --build --preset openharmony-x86_64

      - name: Build project
        run: |
          cp -R resources/projects/openharmony ./

          mkdir -p openharmony/entry/src/main/cpp/third_party/suika3/lib/arm64-v8a
          cp build-openharmony-arm64/libsuika3.a openharmony/entry/src/main/cpp/third_party/suika3/lib/arm64-v8a/

          mkdir -p openharmony/entry/src/main/cpp/third_party/suika3/lib/x86_64
          cp build-openharmony-x86_64/libsuika3.a openharmony/entry/src/main/cpp/third_party/suika3/lib/x86_64/

          mkdir -p openharmony/entry/src/main/resources/rawfile/
          cp -R game/* openharmony/entry/src/main/resources/rawfile/
          cp resources/launcher/system/font/NotoSans-Medium.ttf openharmony/entry/src/main/resources/rawfile/system/font/NotoSansCJK-Medium.ttc

          zip -r Suika3-OpenHarmony-DevEco.zip openharmony

      - name: Upload OpenHarmony artifact
        uses: actions/upload-artifact@v4
        with:
          name: openharmony
          path: |
            Suika3-OpenHarmony-DevEco.zip
          if-no-files-found: error
          retention-days: 7

  build-unity:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache LLVM
        id: cache-llvm-21-v1
        uses: actions/cache@v4
        with:
          path: llvm-21
          key: llvm-21

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build flex bison mingw-w64

      - name: Setup LLVM for Unity
        if: steps.cache-llvm-21-v1.outputs.cache-hit != 'true'
        run: |
          curl -L -o llvm.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.8/LLVM-21.1.8-Linux-X64.tar.xz
          mkdir llvm-21 && tar -xJf llvm.tar.xz -C llvm-21 --strip-components=1

      - name: Setup PATH for LLVM
        run: |
          $(pwd)/llvm-21/bin/clang --version
          echo $(pwd)/llvm-21/bin >> $GITHUB_PATH

      - name: Build for Unity
        run: |
          clang --version
          cmake --preset unity-win64
          cmake --build --preset unity-win64
          cmake --preset unity-switch
          cmake --build --preset unity-switch
          cmake --preset unity-ps5
          cmake --build --preset unity-ps5
          cmake --preset unity-xbox
          cmake --build --preset unity-xbox

      - name: Built project
        run: |
          mkdir unity
          mkdir unity/Assets

          mkdir unity/Assets/StreamingAssets
          cp -R game/* unity/Assets/StreamingAssets/
          cp resources/launcher/system/font/NotoSans-Medium.ttf unity/Assets/StreamingAssets/system/font/NotoSansCJK-Medium.ttc

          mkdir unity/Assets/Resources
          cp external/PlayfieldEngine/external/StratoHAL/src/StratoScript.cs      unity/Assets/
          cp external/PlayfieldEngine/external/StratoHAL/src/NormalShader.shader  unity/Assets/Resources/
          cp external/PlayfieldEngine/external/StratoHAL/src/AddShader.shader     unity/Assets/Resources/
          cp external/PlayfieldEngine/external/StratoHAL/src/DimShader.shader     unity/Assets/Resources/
          cp external/PlayfieldEngine/external/StratoHAL/src/RuleShader.shader    unity/Assets/Resources/
          cp external/PlayfieldEngine/external/StratoHAL/src/MeltShader.shader    unity/Assets/Resources/
          cp external/PlayfieldEngine/external/StratoHAL/src/MainScene.unity      unity/Assets/

          mkdir unity/Assets/Plugins
          mkdir unity/Assets/Plugins/x86_64
          mkdir unity/Assets/Plugins/Switch
          mkdir unity/Assets/Plugins/PS5
          mkdir unity/Assets/Plugins/GameCoreXboxSeries
          mkdir unity/Assets/Plugins/Common
          cp unity-win64/libsuika3.dll unity/Assets/Plugins/x86_64/
          cp unity-switch/libsuika3.a  unity/Assets/Plugins/Switch/
          cp unity-ps5/libsuika3.a     unity/Assets/Plugins/PS5/
          cp unity-xbox/suika3.lib     unity/Assets/Plugins/GameCoreXboxSeries/

          cp docs/readme/unity.md dist/SDK/unity/

          zip -r Suika3-Unity.zip unity

      - name: Upload Unity artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity
          path: |
            Suuka3-Unity.zip
          if-no-files-found: error
          retention-days: 7

  build-mkdocs:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y mkdocs-material

      - name: Run mkdocs
        run: |
          cd docs/mkdocs-en
          mkdocs build
          mv site documents
          tar czf ../../Suika3-documents.zip documents

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs
          path: |
            Suika3-documents.zip
          if-no-files-found: error
          retention-days: 7

  zip:
    if: |
      github.event_name != 'push' ||
      !contains(github.event.head_commit.message, '[docs]')
    needs:
      - build-windows-vs2022
      - build-windows-mingw-w64
      - build-macos
      - build-flatpak-x86_64
      - build-flatpak-aarch64
      - build-wasm
      - build-android
      - build-openharmony
      - build-unity
      - build-mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make the target directory
        run: |
          mkdir dist
          mkdir dist/SDK
          mkdir dist/SDK/windows
          mkdir dist/SDK/macos
          mkdir dist/SDK/macos/project
          mkdir dist/SDK/linux
          mkdir dist/SDK/wasm
          mkdir dist/SDK/ios
          mkdir dist/SDK/android
          mkdir dist/SDK/openharmony
          mkdir dist/SDK/unity

      - name: Copy the sample game
        run: |
          cp -R game/.vscode dist/
          cp game/main.ray dist/
          cp game/start.novel dist/
          cp game/config.ini dist/
          cp -R game/images dist/
          cp -R game/sound dist/
          cp -R game/system dist/

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-binaries
          path: windows

      - name: Download mingw artifacts
        uses: actions/download-artifact@v4
        with:
          name: mingw
          path: mingw

      - name: Copy for Windows
        run: |
          cp windows/suika3-win64.exe   dist/
          cp windows/suika3-win64.exe   dist/SDK/windows/suika3-win64.exe
          cp mingw/suika3-win32.exe     dist/SDK/windows/suika3-win32.exe
          cp windows/suika3-pack.exe    dist/SDK/windows/
          cp windows/suika3-web.exe     dist/SDK/wasm/
          cp windows/suika3-arm64.exe   dist/SDK/windows/suika3-arm64.exe
          cp windows/suika3-debug.exe   dist/SDK/windows/suika3-debug.exe

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos
          path: macos

      - name: Copy for macOS
        run: |
          cp macos/Suika3.dmg dist/SDK/macos/

          mkdir dist/SDK/macos/project
          cp macos/Suika3-macOS-Xcode.zip -d dist/SDK/macos
          mv dist/SDK/macos/macos dist/SDK/macos/project

          mkdir dist/SDK/macos/root
          tar xzf suika3-macos-universal.tar.gz  -C dist/SDK/macos/root

          cp dist/SDK/macos/root/bin/suika3-aotc    dist/SDK/macos/
          cp dist/SDK/macos/root/bin/suika3-bcc     dist/SDK/macos/
          cp dist/SDK/macos/root/bin/suika3-pack    dist/SDK/macos/
          cp resources/macos/suika3-wrapper.sh      dist/SDK/macos/

      - name: Copy for iOS
        run: |
          mkdir dist/SDK/ios/project
          cp macos/Suika3-iOS-Xcode.zip -d dist/SDK/ios
          mv dist/SDK/ios/ios dist/SDK/ios/project

      - name: Download Flatpak x86_64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: flatpak-x86_64
          path: flatpak-x86_64

      - name: Download Flatpak aarch64 artifacts
        uses: actions/download-artifact@v4
        with:
          name: flatpak-aarch64
          path: flatpak-aarch64

      - name: Copy for Linux
        run: |
          cp flatpak-x86_64/Suika3-x86_64.flatpak dist/SDK/linux/
          cp flatpak-aarch64/Suika3-aarch.flatpak dist/SDK/linux/
          cp resources/linux/suika3-wrapper.sh dist/SDK/linux/

      - name: Download wasm artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm
          path: wasm

      - name: Copy for Wasm.
        run: |
          cp wasm/index.html dist/SDK/wasm/
          cp resources/assets.arc dist/SDK/wasm/
          cp wasm/index.html suika3-wasm.html

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android
          path: android

      - name: Copy for Android
        run: |
          zip -x android/Suika3-Android-Studio.zip -d dist/SDK

      - name: Download OpenHarmony artifacts
        uses: actions/download-artifact@v4
        with:
          name: openharmony
          path: openharmony

      - name: Copy for OpenHarmony
        run: |
          zip -x openharmony/Suika3-OpenHarmony-DevEco.zip -d dist/SDK

      - name: Download Unity artifacts
        uses: actions/download-artifact@v4
        with:
          name: unity
          path: unity

      - name: Copy for Unity
        run: |
          zip -x unity/Suika3-Unity.zip -d dist/SDK

      - name: Download mkdocs artifacts
        uses: actions/download-artifact@v4
        with:
          name: mkdocs
          path: mkdocs

      - name: Copy documents
        run: |
          zip -x mkdocs/Suika3-documents.zip -C dist/SDK/
          cp README.md dist/SDK/

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Make documents
        run: |
          mv dist Suika3
          7z a -tzip -mx=9 Suika3-SDK-Full.zip Suika3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: CI-${{ env.DATE }}-${{ env.SHORT_SHA }}
          name: Suika3-CI-${{ env.DATE }}-${{ env.SHORT_SHA }}
          prerelease: true
          files: |
            Suika3-SDK-Full.zip
            windows/suika3-win64.exe
            mingw/suika3-win32.exe
            macos/Suika3.dmg
            macos/Suika3-macOS-Xcode.zip
            linux/Suika3-x86_64.flatpak
            linux/Suika3-aarch64.flatpak
            macos/Suika3-iOS-Xcode.zip
            android/Suika3-Android-Studio.zip
            openharmony/Suika3-OpenHarmony-DevEco.zip
            wasm/suika3-wasm.html
            unity/Suika3-Unity.zip

          body: |
            - This is an automated build from CI and is not an official release.
